export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_USER = "LOGIN_USER";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SOCIAL_LOGIN_ERROR = "SOCIAL_LOGIN_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";
